// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using msg.server;

namespace msg.server.MsgD1Migrations
{
    [DbContext(typeof(MSGContext))]
    [Migration("20190510121238_CreateMsgDatabase")]
    partial class CreateMsgDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("msg.lib.Dialogue", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.HasKey("ID");

                    b.ToTable("Dialogues");
                });

            modelBuilder.Entity("msg.lib.Member", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("DialogueID");

                    b.HasKey("ID");

                    b.HasIndex("DialogueID");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("msg.lib.Message", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("DialogueID");

                    b.Property<DateTime>("SentAt");

                    b.Property<Guid>("SentBy");

                    b.Property<string>("Text");

                    b.HasKey("ID");

                    b.HasIndex("DialogueID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("msg.lib.Member", b =>
                {
                    b.HasOne("msg.lib.Dialogue")
                        .WithMany("Members")
                        .HasForeignKey("DialogueID");
                });

            modelBuilder.Entity("msg.lib.Message", b =>
                {
                    b.HasOne("msg.lib.Dialogue", "Dialogue")
                        .WithMany()
                        .HasForeignKey("DialogueID");
                });
#pragma warning restore 612, 618
        }
    }
}
